title: My Amazing Blog
author: Tasnim Musanna
email: tmusa1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  My website is an amazing place where you can read about me. It is very entertaining. Subscribe to my newsletter!!!

# social links
twitter_username: I don't have twitter :(
github_username:  @tasnimmusanna

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
